### ISSUE TITLE
0301_문제

### ISSUE THREAD

**Issue by hi-jade88** [tuesdayCoding/homework#1]

**Comment by hi-jade88** [comment]
Lv2. [메뉴리뉴얼](https://programmers.co.kr/learn/courses/30/lessons/72411)
Lv2. [행렬 테두리 회전하기](https://programmers.co.kr/learn/courses/30/lessons/77485)
Lv2. [괄호 변환](https://programmers.co.kr/learn/courses/30/lessons/60058)
Lv3. [모두 0으로 만들기](https://programmers.co.kr/learn/courses/30/lessons/76503)

**Comment by joonfluence** [comment]
Lv1. [체육복](https://programmers.co.kr/learn/courses/30/lessons/42862)
Lv2. [타겟 넘버](https://programmers.co.kr/learn/courses/30/lessons/43165)
Lv3. [정수 삼각형](https://programmers.co.kr/learn/courses/30/lessons/43105)
LV3. [네트워크](https://programmers.co.kr/learn/courses/30/lessons/43162)

**Comment by paulleelife** [comment]
Lv2. [기능개발](https://programmers.co.kr/learn/courses/30/lessons/42586)
Lv2. [프린터](https://programmers.co.kr/learn/courses/30/lessons/42587)
Lv3. [가장 먼 노드](https://programmers.co.kr/learn/courses/30/lessons/49189)
Lv4. [도둑질](https://programmers.co.kr/learn/courses/30/lessons/42897)

**Comment by npcnc-heejin** [comment]
Lv1. [음양 더하기](https://programmers.co.kr/learn/courses/30/lessons/76501)
Lv1. [약수의 개수와 덧셈](https://programmers.co.kr/learn/courses/30/lessons/77884)
Lv1. [x만큼 간격이 있는 n개의 숫자](https://programmers.co.kr/learn/courses/30/lessons/12954)
Lv1. [최대공약수와 최소공배수](https://programmers.co.kr/learn/courses/30/lessons/12940)

**Comment by h2jinee** [comment]
Lv1. [음양 더하기](https://programmers.co.kr/learn/courses/30/lessons/76501)
Lv1. [약수의 개수와 덧셈](https://programmers.co.kr/learn/courses/30/lessons/77884)
Lv1. [x만큼 간격이 있는 n개의 숫자](https://programmers.co.kr/learn/courses/30/lessons/12954)
Lv1. [최대공약수와 최소공배수](https://programmers.co.kr/learn/courses/30/lessons/12940)
