### ISSUE TITLE
0308_문제

### ISSUE THREAD

**Issue by hi-jade88** [tuesdayCoding/homework#2]

**Comment by joonfluence** [comment]
LV2. [더 맵게](https://programmers.co.kr/learn/courses/30/lessons/42626)
LV3. [N으로 표현](https://programmers.co.kr/learn/courses/30/lessons/42895)
LV3. [네트워크](https://programmers.co.kr/learn/courses/30/lessons/43162)
LV3. [여행경로](https://programmers.co.kr/learn/courses/30/lessons/43164)

**Comment by hi-jade88** [comment]
LV2. [문자열 압축](https://programmers.co.kr/learn/courses/30/lessons/60057?language=javascript)
LV2. [영어끝말잇기](https://programmers.co.kr/learn/courses/30/lessons/12981)
Lv1. [JadenCase 문자열 만들기](https://programmers.co.kr/learn/courses/30/lessons/12951)
Lv3. [이중우선순위큐](https://programmers.co.kr/learn/courses/30/lessons/42628)

**Comment by paulleelife** [comment]
LV2. [다리를 지나는 트럭](https://programmers.co.kr/learn/courses/30/lessons/42583)
LV2. [주식가격](https://programmers.co.kr/learn/courses/30/lessons/42584)
LV3. [순위](https://programmers.co.kr/learn/courses/30/lessons/49191)
LV5. [방의 개수](https://programmers.co.kr/learn/courses/30/lessons/49190)
